### ISSUE TITLE
Add width and height by default on image

### ISSUE THREAD

**Issue by Romaixn** [sulu/web-twig#35]
It would be cool if, by default, we added the width and height of the image, in accordance with good HTML practices.

Like : `<img alt="Test" title="Test" src="/uploads/media/sulu-100x100/01/image.jpg?v=1-0" width="100" height="100">`

**Comment by alexander-schranz** [comment]
Was also thinking about this as since Sulu `2.3` we have the width and height of the original files which we could use for this calculate the size. For BC reasons it need to be an activate option in the constructor, so it will not crash exist projects which do not expect the width and height to be included.

**Comment by alexander-schranz** [comment]
This will be fixed by #36

**Comment by nnatter** [comment]
Thanks for reporting - fixed in #36 🙂
